//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetBanking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternetBanking()
        {
            this.IB_TaiKhoan = new HashSet<IB_TaiKhoan>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string KhachHang { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IB_TaiKhoan> IB_TaiKhoan { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
    }
}
