//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTK
    {
        public string ID { get; set; }
        public string KhachHang { get; set; }
        public Nullable<int> SoDu { get; set; }
        public Nullable<int> KyHan { get; set; }
        public Nullable<double> LaiSuat { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string TaiKhoanLienKet { get; set; }
        public string ChiNhanh { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ChiNhanh ChiNhanh1 { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual TKTT TKTT { get; set; }
    }
}
