//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKTT()
        {
            this.IB_TaiKhoan = new HashSet<IB_TaiKhoan>();
            this.The_TaiKhoan = new HashSet<The_TaiKhoan>();
            this.TKTKs = new HashSet<TKTK>();
        }
    
        public string ID { get; set; }
        public string KhachHang { get; set; }
        public string ChiNhanh { get; set; }
        public Nullable<int> SoDu { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ChiNhanh ChiNhanh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IB_TaiKhoan> IB_TaiKhoan { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<The_TaiKhoan> The_TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKTK> TKTKs { get; set; }
    }
}
