//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUIBANK_WEBAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customer_Account
    {
        public string customername { get; set; }
        public string accountnumber { get; set; }
        public int accountbalance { get; set; }
        public string branchname { get; set; }
    }
}
