//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiNhanh
    {
        public ChiNhanh()
        {
            this.KhachHangs = new HashSet<KhachHang>();
            this.NhanViens = new HashSet<NhanVien>();
            this.TKTTs = new HashSet<TKTT>();
            this.TKTKs = new HashSet<TKTK>();
        }
    
        public string ID { get; set; }
        public string TenCN { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        public virtual ICollection<TKTT> TKTTs { get; set; }
        public virtual ICollection<TKTK> TKTKs { get; set; }
    }
}
