//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.InternetBankings = new HashSet<InternetBanking>();
            this.TKTTs = new HashSet<TKTT>();
            this.Thes = new HashSet<The>();
            this.TKTKs = new HashSet<TKTK>();
        }
    
        public string ID { get; set; }
        public string Hoten { get; set; }
        public string ChiNhanh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ChiNhanh ChiNhanh1 { get; set; }
        public virtual ICollection<InternetBanking> InternetBankings { get; set; }
        public virtual ICollection<TKTT> TKTTs { get; set; }
        public virtual ICollection<The> Thes { get; set; }
        public virtual ICollection<TKTK> TKTKs { get; set; }
    }
}
