//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan
{
    using System;
    using System.Collections.Generic;
    
    public partial class The
    {
        public The()
        {
            this.The_TaiKhoan = new HashSet<The_TaiKhoan>();
        }
    
        public string ID { get; set; }
        public string Password { get; set; }
        public string KhachHang { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual ICollection<The_TaiKhoan> The_TaiKhoan { get; set; }
    }
}
