//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanTan
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_TaiKhoan
    {
        public string The { get; set; }
        public string TaiKhoan { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual The The1 { get; set; }
        public virtual TKTT TKTT { get; set; }
    }
}
